jobs:
- job: BUILD_SSDSIM
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio
    - vstest
  steps:
  - script: 'npm install'
  - script: 'printenv'
  - script: |
      echo "##vso[task.setvariable variable=AZUREDEVOPSBUILDID;isOutput=true]$(Build.ContainerId)"
    name: stepSetAzureDevopsBuildID
  - script: |
      echo "$(stepSetAzureDevopsBuildID.AZUREDEVOPSBUILDID)"
  - script: git clone https://github.com/DustParticle/SsdSim.git
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
  - task: VSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: release
      platform: x64
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: x64Release
      pathtoPublish: ./SsdSim/x64/Release/


- job: UNIT_TEST
  dependsOn: BUILD_SSDSIM
  variables:
    # Define the variable AZUREDEVOPSBUILDID from the previous job
    AZUREDEVOPSBUILDID: $[ dependencies.BUILD_SSDSIM.outputs['stepSetAzureDevopsBuildID.AZUREDEVOPSBUILDID'] ]
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio
    - vstest
  steps:
  - script: 'npm install'
  - script: 'printenv'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'SsdSim'
      pipeline: 'SsdSim-CI'
      buildVersionToDownload: 'specific'
      buildId: $(AZUREDEVOPSBUILDID)
      artifactName: x64Release
      downloadPath: $(System.DefaultWorkingDirectory)
  - powershell: 'x64Release/Test.exe'


