jobs:
- job: BUILD_SSDSIM
  condition: eq(variables['JobName'], 'BUILD_SSDSIM')
  steps:
  - script: 'npm install'
  - script: 'node updateBeginJob.js "$(RiverflowApiKey)"'
  - script: 'printenv'
  - script: git clone https://github.com/DustParticle/SsdSim.git
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
  - task: VSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: release
      platform: x64
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: x64Release
      pathtoPublish: ./SsdSim/x64/Release/
  - script: 'node updateEndJob.js "$(RiverflowApiKey)"'


- job: UNIT_TEST
  condition: eq(variables['JobName'], 'UNIT_TEST')
  steps:
  - script: 'npm install'
  - script: 'node updateBeginJob.js "$(RiverflowApiKey)"'
  - script: 'printenv'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'SsdSim'
      pipeline: 'SsdSim-CI'
      buildVersionToDownload: 'specific'
      buildId: 344
      artifactName: x64Release
      downloadPath: $(System.DefaultWorkingDirectory)
  - powershell: 'x64Release/Test.exe'
  - script: 'node updateEndJob.js "$(RiverflowApiKey)"'


