jobs:
- job: BUILD_SSDSIM
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio
    - vstest
  steps:
  - script: 'npm install'
  - script: 'printenv'
  - script: git clone https://github.com/DustParticle/SsdSim.git
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
  - task: VSBuild@1
    displayName: 'Build solution **/*.sln'
    inputs:
      configuration: release
      platform: x64
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: x64Release
      pathtoPublish: ./SsdSim/x64/Release/


- job: UNIT_TEST
  dependsOn: BUILD_SSDSIM
  pool:
    name: Hosted Windows Container
  condition: eq(variables['JobName'], 'UNIT_TEST')
  steps:
  - script: 'npm install'
  - script: 'printenv'
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'SsdSim'
      pipeline: 'SsdSim-CI'
      buildVersionToDownload: 'specific'
      artifactName: x64Release
      downloadPath: $(System.DefaultWorkingDirectory)
  - powershell: 'x64Release/Test.exe'


