jobs:
- job: BUILD
  strategy:
    maxParallel: 1
    matrix: 
      x64_Debug:
        BuildConfiguration: debug
        BuildPlatform: x64
        TestExe: './SsdSim/x64/Debug/Test.exe'
        ArtifactPath: './SsdSim/x64/Debug/'
        ArtifactName: 'x64Debug'
  steps:
  - script: git clone https://github.com/DustParticle/SsdSim.git
  - script: printenv

